### ISSUE TITLE
Draw Rectangle

### ISSUE THREAD

**Issue by ChaseMarsh** [BlakeAndrew/Map-Drawings-#2]
As a user, I would like the ability to draw a rectangle, so that I can designate an air corridor.

I would like to do this via a touch/drag gesture. Meaning, I touch the screen to lock in a corner, then drag away from that point to create a rectangle. The point at which I touched could become any of the four corners of the rectangle.

**Comment by BlakeAndrew** [comment]
Feature has now been added and pushed into the master branch
